; =====================================================================
; Asterisk ACL Configuration
; =====================================================================

[BASELINE]
type=acl
permit=0.0.0.0/0.0.0.0
