; =====================================================================
; Asterisk ACL Configuration
; =====================================================================

[BASELINE]
permit=0.0.0.0/0.0.0.0
