[general]
dateformat=%F %T

[logfiles]
; Send call notices, warnings, errors, and verbose call execution steps to Docker console
console => notice,warning,error,dtmf,verbose
messages => notice,warning,error
