[modules]
autoload=yes

; Disable legacy chan_sip driver
noload => chan_sip.so

; Disable ARI child modules
noload => res_ari.so
noload => res_ari_model.so
noload => res_ari_applications.so
noload => res_ari_asterisk.so
noload => res_ari_bridges.so
noload => res_ari_channels.so
noload => res_ari_device_states.so
noload => res_ari_endpoints.so
noload => res_ari_events.so
noload => res_ari_playbacks.so
noload => res_ari_recordings.so
noload => res_ari_sounds.so

; Disable unneeded drivers and databases
noload => res_xmpp.so
noload => chan_motif.so
noload => chan_alsa.so
noload => chan_oss.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => res_pjsip_transport_websocket.so
noload => cel_tds.so
noload => cdr_tds.so
noload => cel_radius.so
noload => cdr_radius.so
noload => cel_sqlite3_custom.so
noload => cdr_sqlite3_custom.so
noload => cel_pgsql.so
noload => cdr_pgsql.so
noload => res_hep_rtcp.so
noload => res_hep_pjsip.so
noload => pbx_dundi.so
noload => res_config_ldap.so
noload => res_stun_monitor.so

; Disable deprecated modules
noload => app_macro.so
noload => res_monitor.so
noload => chan_mgcp.so
noload => res_adsi.so
noload => app_adsiprog.so
noload => app_getcpeid.so
noload => app_ices.so
noload => app_url.so
noload => app_image.so
noload => app_nbscat.so
