[modules]
autoload=yes

; =====================================================================
; 1. Disabled modules
; =====================================================================
noload => chan_skinny.so
noload => chan_unistim.so
noload => res_pjsip_transport_websocket.so
noload => cel_tds.so
noload => cdr_tds.so
noload => cel_radius.so
noload => cdr_radius.so
noload => cel_sqlite3_custom.so
noload => cdr_sqlite3_custom.so
noload => cel_pgsql.so
noload => cdr_pgsql.so
noload => res_hep_rtcp.so
noload => res_hep_pjsip.so
noload => pbx_dundi.so

; =====================================================================
; 2. Disable deprecated / obsolete modules warning in your logs
; =====================================================================
noload => res_monitor.so
noload => chan_mgcp.so
noload => res_adsi.so
noload => app_adsiprog.so
noload => app_getcpeid.so
noload => app_ices.so
noload => app_url.so
noload => app_image.so
noload => app_nbscat.so

; =====================================================================
; 3. Disable unused services (LDAP, ARI, XMPP, STUN)
; =====================================================================
noload => res_config_ldap.so
noload => res_ari.so
noload => res_xmpp.so
noload => res_stun_monitor.so
