[general]
externip=193.89.248.25
context=incoming

allow=ulaw
allow=alaw
allow=gsm

register => $SIP_TRUNK_USERNAME:$SIP_TRUNK_SECRET@$SIP_TRUNK_HOST/$SIP_TRUNK_USERNAME

[sip-trunk]
type=peer
secret=$SIP_TRUNK_SECRET
defaultuser=$SIP_TRUNK_USERNAME
fromuser=$SIP_TRUNK_USERNAME
host=$SIP_TRUNK_HOST
fromdomain=$SIP_TRUNK_HOST
dtmfmode=rfc2833
canreinvite=no
disallow=all
allow=ulaw
allow=alaw
allow=gsm
insecure=port,invite
context=incoming
nat=force_rport,comedia
qualify=yes

[1000]
type=friend
defaultuser=stoffer
secret=EizaH6ae
dtmfmode=rfc2833
callerid="First Phone" <1000>
host=dynamic
canreinvite=no
deny=0.0.0.0/0.0.0.0
permit=10.8.0.0/255.255.255.0,192.168.0.0/255.255.0.0
context=myphones

[1001]
type=friend
defaultuser=1001
secret=lae2Aaph
dtmfmode=rfc2833
callerid="Second Phone" <1001>
host=dynamic
canreinvite=no
deny=0.0.0.0/0.0.0.0
permit=10.8.0.0/255.255.255.0,192.168.0.0/255.255.0.0
context=myphones
